name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Armbian build framework"
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          fetch-depth: 0
          clean: false
      - uses: armbian/build@main
        name: "Build Armbian"
        with:
          armbian_token:         "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:       "jammy"                        # userspace
          armbian_target:        "build"                        # build=image, kernel=kernel
          armbian_board:         "orangepi5-plus"               # build target
          armbian_kernel_branch: "legacy"                       # legacy,current,edge
          armbian_ui:            "server"
          armbian_extensions:    "v4l2loopback-dkms,mesa-vpu"
          
