name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: armbian/build@v24.8.0-trunk.132
        name: "Build Armbian"
        with:
          armbian_token:         "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:       "jammy"                        # userspace
          armbian_target:        "build"                        # build=image, kernel=kernel
          armbian_board:         "orangepi5-plus"               # build target
          armbian_kernel_branch: "legacy"                       # legacy,vendor,current,edge
          armbian_ui:            "server"
          armbian_extensions:    "v4l2loopback-dkms,mesa-vpu"
          
