name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    strategy:
      matrix:
        kernel: [vendor, current]
        os: [jammy, noble, bookworm]
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'
      - name: Build
        run: |
          echo "Free space:"
          df -h
      - uses: armbian/build@v24.8.0-trunk.132
        name: "Build Armbian"
        with:
          armbian_token:         "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:       ${{ matrix.os }}               # userspace
          armbian_target:        "build"                        # build=image, kernel=kernel
          armbian_board:         "orangepi5-plus"               # build target
          armbian_kernel_branch: ${{ matrix.kernel }}           # legacy,vendor,current,edge
          armbian_ui:            "server"
          armbian_extensions:    "v4l2loopback-dkms,mesa-vpu"
